### ISSUE TITLE
Using $HOME/bin versus $HOME/.local/bin

### ISSUE THREAD

**Issue by tseemann** [andersgs/kraken-trawl#14]
The instructions have  `--install-option="--install-scripts=$HOME/bin"`

Have you told users to add `$HOME/bin` to their PATH ?

I thought pip defaulted to `$HOME/.local/bin` ?

**Comment by andersgs** [comment]
That is correct... By default `pip install --user` will install in `$HOME/.local/bin`.

But, sometimes, we don't want the `default` location, and that is why I have that example, as noted in the line above that one in `README`:

`Use the --install-option to install the script in a particular location:`

**Comment by tseemann** [comment]
If you don't tell people how to add it to their PATH you will get emails about this error:

```
% pip install ....
% kraken-trawl
Command not found
```

Just sayin' :)

**Comment by andersgs** [comment]
![](https://media.tenor.co/images/daaf88c2f851a39c5ec44b79bcf60956/raw)
